### ISSUE TITLE
Sometimes doesn't load

### ISSUE THREAD

**Issue by wizonesolutions** [drew-y/meteor-autoform-datetimepicker#1]
I have this init code:

``` javascript
Template.Home.onRendered(function () {
  this.$('#start').datetimepicker();
});
```

and this HTML

``` html
        <div>
          <label for="start">Start date/time</label>
          <input name="start" type="text" id="start">
        </div>
```

No error messages in the console. If I init it manually when it's not working, it works fine. It seems like a race condition, but that doesn't make sense because doesn't `onRendered` run after the DOM is ready?

**Comment by drew-y** [comment]
Are you using datetimepicker with autoform? You shouldn't need to manually initialize it with jQuery if you are. Generally you'd initialize it by setting the type in your schema like so:

``` javascript
Schema.Date = new SimpleSchema({
  date: {
    type: String,
    autoForm: {
      type: 'datetimepicker'
    }
  }
});
```

Otherwise you may be looking for the [meteor-datetimepicker](https://github.com/drew-y/meteor-datetimepicker) repository. if thats the case create an issue over there and I'll look into reproducing it. 

On a side note try removing 'this' from your code. 

``` javascript
Template.Home.onRendered(function () {
  $('#start').datetimepicker();
});
```

Hope this helps.

**Comment by wizonesolutions** [comment]
Whoops, sorry for wrong repo!
